gps_imu_node:
  ros__parameters:
    host: 192.168.1.172
    port: 60570
    gps_topic: /mobile_navigation/gps
    imu_topic: /mobile_navigation/imu
    twist_topic: /mobile_navigation/twist
    debug: True