name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: install pre-commit
      run: |
        npm install
        pip install --upgrade pip
        pip install pre-commit jupyter djhtml
        pre-commit install
    - name: run pre-commit hooks
      run: |
        pre-commit run --color=always --all-files
